### ISSUE TITLE
Data not available

### ISSUE THREAD

**Issue by doujzc** [facebookresearch/GraphLog#34]
The url https://www.cs.mcgill.ca/~ksinha4/data/graphlog_v1.1.zip in the repository.json file seems to be no longer available. Would it be possible for the author to update it or upload the graphlog data?

**Comment by koustuvsinha** [comment]
Apologies for the delay - somehow I missed the notifications from this repo. Here is the link to the data: https://drive.google.com/file/d/1s6oG_5Ul199puKAu67z3QrOAm943hGV2/view?usp=sharing
