### ISSUE TITLE
您好，数据集链接https://www.cs.mcgill.ca/~ksinha4/data/graphlog_icml_data.zip无效

### ISSUE THREAD

**Issue by liangye20** [facebookresearch/GraphLog#35]

**Comment by koustuvsinha** [comment]
I'm sorry I do not understand Mandarin, but if you were looking for the data I have re-uploaded them here: https://drive.google.com/file/d/1s6oG_5Ul199puKAu67z3QrOAm943hGV2/view?usp=sharing
